# 2413998 Pratik Shrestha


## Worksheet 0

## 4.1 Exercises on Functions

## Task 1

In [1]:
def convert_units(conversion_type, value):
    """
    Converts units based on the selected conversion type.

    Parameters:
    conversion_type (str): The type of conversion selected by the user.
    value (float): The numeric value that needs to be converted.

    Returns:
    float: The converted value.
    """

    if conversion_type == "1":
        return value * 3.28084
    elif conversion_type == "2":
        return value / 3.28084
    elif conversion_type == "3":
        return value * 2.20462
    elif conversion_type == "4":
        return value / 2.20462
    elif conversion_type == "5":
        return value * 0.264172
    elif conversion_type == "6":
        return value / 0.264172
    else:
        return None



print("Unit Conversion Program")
print("------------------------")
print("1. Meters (m) to Feet (ft)")
print("2. Feet (ft) to Meters (m)")
print("3. Kilograms (kg) to Pounds (lbs)")
print("4. Pounds (lbs) to Kilograms (kg)")
print("5. Liters (L) to Gallons (gal)")
print("6. Gallons (gal) to Liters (L)")

conversion_type = input("Choose a conversion option (1-6): ")

try:
    value = float(input("Enter the value to convert: "))

    result = convert_units(conversion_type, value)

    if result is None:
        print("Error: Unsupported conversion type.")
    else:
        print(f"Converted value: {result:.2f}")

except ValueError:
    print("Error: Please enter a valid numeric value.")


Unit Conversion Program
------------------------
1. Meters (m) to Feet (ft)
2. Feet (ft) to Meters (m)
3. Kilograms (kg) to Pounds (lbs)
4. Pounds (lbs) to Kilograms (kg)
5. Liters (L) to Gallons (gal)
6. Gallons (gal) to Liters (L)
Choose a conversion option (1-6): 1
Enter the value to convert: 32
Converted value: 104.99


## Task 2

In [2]:
def find_sum(numbers):
    """
    Calculates the sum of a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The sum of all numbers in the list.
    """
    return sum(numbers)


def find_average(numbers):
    """
    Calculates the average of a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The average of the numbers in the list.
    """
    return sum(numbers) / len(numbers)


def find_maximum(numbers):
    """
    Finds the maximum value in a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The largest number in the list.
    """
    return max(numbers)


def find_minimum(numbers):
    """
    Finds the minimum value in a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The smallest number in the list.
    """
    return min(numbers)


print("Mathematical Operations on a List")
print("---------------------------------")
print("1. Find Sum")
print("2. Find Average")
print("3. Find Maximum")
print("4. Find Minimum")

choice = input("Choose an operation (1-4): ")

try:
    user_input = input("Enter numbers separated by spaces: ")
    numbers = [float(num) for num in user_input.split()]

    if len(numbers) == 0:
        raise ValueError("Empty list")

    if choice == "1":
        result = find_sum(numbers)
        print("Sum:", result)
    elif choice == "2":
        result = find_average(numbers)
        print("Average:", result)
    elif choice == "3":
        result = find_maximum(numbers)
        print("Maximum:", result)
    elif choice == "4":
        result = find_minimum(numbers)
        print("Minimum:", result)
    else:
        print("Error: Invalid operation selected.")

except ValueError:
    print("Error: Please enter valid numbers separated by spaces.")

Mathematical Operations on a List
---------------------------------
1. Find Sum
2. Find Average
3. Find Maximum
4. Find Minimum
Choose an operation (1-4): 3
Enter numbers separated by spaces: 12 24
Maximum: 24.0


## 4.2 Exercise on List Manipulation:

## 1. Extract Every Other Element

In [3]:
def extract_every_other(lst):
    """
    Returns every other element from the given list, starting from the first element.

    Parameters:
    lst (list): The input list from which elements will be extracted.

    Returns:
    list: A new list containing every other element from the original list.
    """
    return lst[::2] # Slicing the list by setting the step to 2


numbers = [1, 2, 3, 4, 5, 6]
result = extract_every_other(numbers)

print("Original list:", numbers)
print("Every other element:", result)

Original list: [1, 2, 3, 4, 5, 6]
Every other element: [1, 3, 5]


## 2. Slice a Sublist:

In [4]:
def get_sublist(lst, start, end):
    """
    Returns a sublist from the given list starting at index 'start'
    and ending at index 'end' (inclusive).

    Parameters:
    lst (list): The original list.
    start (int): The starting index.
    end (int): The ending index.

    Returns:
    list: A sublist from start to end.
    """
    return lst[start:end+1]


numbers = [1, 2, 3, 4, 5, 6]
result = get_sublist(numbers, 2, 4)

print("Original list:", numbers)
print("Sublist:", result)

Original list: [1, 2, 3, 4, 5, 6]
Sublist: [3, 4, 5]


## 3. Reverse a List Using Slicing:

In [5]:
def reverse_list(lst):
    """
    Returns the reversed version of the given list using slicing.

    Parameters:
    lst (list): The list to be reversed.

    Returns:
    list: A new list containing the elements of the original list in reverse order.
    """
    return lst[::-1]


numbers = [1, 2, 3, 4, 5]
result = reverse_list(numbers)

print("Original list:", numbers)
print("Reversed list:", result)

Original list: [1, 2, 3, 4, 5]
Reversed list: [5, 4, 3, 2, 1]


## 4. Remove the First and Last Elements:

In [6]:
def remove_first_last(lst):
    """
    Removes the first and last elements from a list.

    Parameters:
    lst (list): The original list.

    Returns:
    list: A new list without the first and last elements.
    """
    return lst[1:-1]


numbers = [1, 2, 3, 4, 5]
result = remove_first_last(numbers)

print("Original list:", numbers)
print("After removing first and last:", result)

Original list: [1, 2, 3, 4, 5]
After removing first and last: [2, 3, 4]


## 5. Get the First n Elements:

In [7]:
def get_first_n(lst, n):
    """
    Returns the first n elements from a list.

    Parameters:
    lst (list): The original list.
    n (int): The number of elements to extract.

    Returns:
    list: A list containing the first n elements.
    """
    return lst[:n]


numbers = [1, 2, 3, 4, 5]
result = get_first_n(numbers, 3)

print("Original list:", numbers)
print("First n elements:", result)

Original list: [1, 2, 3, 4, 5]
First n elements: [1, 2, 3]


## 6. Extract Elements from the End:

In [8]:
def get_last_n(lst, n):
    """
    Returns the last n elements from a list.

    Parameters:
    lst (list): The original list.
    n (int): The number of elements to extract from the end.

    Returns:
    list: A list containing the last n elements.
    """
    return lst[-n:]


numbers = [1, 2, 3, 4, 5]
result = get_last_n(numbers, 2)

print("Original list:", numbers)
print("Last n elements:", result)

Original list: [1, 2, 3, 4, 5]
Last n elements: [4, 5]


## 7. Extract Elements in Reverse Order:

In [9]:
def reverse_skip(lst):
    """
    Returns every second element from the list starting from the second-to-last element,
    moving backward.

    Parameters:
    lst (list): The original list.

    Returns:
    list: A new list containing elements in reverse order, skipping one element each time.
    """
    return lst[-2::-2]


numbers = [1, 2, 3, 4, 5, 6]
result = reverse_skip(numbers)

print("Original list:", numbers)
print("Reversed skip list:", result)

Original list: [1, 2, 3, 4, 5, 6]
Reversed skip list: [5, 3, 1]


# 4.3 Exercise on Nested List:

## 1. Flatten a Nested List:

In [10]:
def flatten(lst):
    """
    Flattens a nested list into a single list with all elements in one dimension.

    Parameters:
    lst (list): A nested list (list of lists).

    Returns:
    list: A flattened list containing all elements from the nested lists.
    """
    flat_list = []
    for sublist in lst:
        for item in sublist:
            flat_list.append(item)
    return flat_list


nested_list = [[1, 2], [3, 4], [5]]
result = flatten(nested_list)

print("Original nested list:", nested_list)
print("Flattened list:", result)

Original nested list: [[1, 2], [3, 4], [5]]
Flattened list: [1, 2, 3, 4, 5]


## 2. Accessing Nested List Elements:


In [11]:
def access_nested_element(lst, indices):
    """
    Accesses an element from a nested list using a list of indices.

    Parameters:
    lst (list): The nested list.
    indices (list): A list of indices to access the desired element.

    Returns:
    element: The element at the specified position in the nested list.
    """
    element = lst
    for index in indices:
        element = element[index]
    return element


nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]
result = access_nested_element(nested_list, indices)

print("Nested list:", nested_list)
print("Indices:", indices)
print("Accessed element:", result)

Nested list: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Indices: [1, 2]
Accessed element: 6


## 3. Sum of All Elements in a Nested List:

In [12]:
def sum_nested(lst):
    """
    Calculates the sum of all numbers in a nested list, including nested sublists.

    Parameters:
    lst (list): A nested list containing numbers and/or other lists.

    Returns:
    int/float: The sum of all numbers in the nested list.
    """
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

nested_list = [[1, 2], [3, [4, 5]], 6]
result = sum_nested(nested_list)

print("Nested list:", nested_list)
print("Sum of all elements:", result)

Nested list: [[1, 2], [3, [4, 5]], 6]
Sum of all elements: 21


## 4. Remove Specific Element from a Nested List:

In [13]:
def remove_element(lst, elem):
    """
    Removes all occurrences of a specific element from a nested list.

    Parameters:
    lst (list): The nested list.
    elem: The element to remove.

    Returns:
    list: The modified list with all occurrences of elem removed.
    """
    new_list = []
    for item in lst:
        if isinstance(item, list):
            new_list.append(remove_element(item, elem))
        else:
            if item != elem:
                new_list.append(item)
    return new_list


nested_list = [[1, 2], [3, 2], [4, 5]]
result = remove_element(nested_list, 2)

print("Original list:", nested_list)
print("Modified list:", result)

Original list: [[1, 2], [3, 2], [4, 5]]
Modified list: [[1], [3], [4, 5]]


## 5. Find the Maximum Element in a Nested List:

In [14]:
def find_max(lst):
    """
    Finds the maximum element in a nested list, including all sublists.

    Parameters:
    lst (list): A nested list containing numbers and/or other lists.

    Returns:
    int/float: The maximum value in the nested list.
    """
    max_val = 0

    for item in lst:
        if isinstance(item, list):
            sub_max = find_max(item)
            if sub_max > max_val:
                max_val = sub_max
        else:
            if item > max_val:
                max_val = item

    return max_val

nested_list = [[1, 2], [3, [4, 5]], 6]
result = find_max(nested_list)

print("Nested list:", nested_list)
print("Maximum element:", result)

Nested list: [[1, 2], [3, [4, 5]], 6]
Maximum element: 6


## 6. Count Occurrences of an Element in a Nested List:


In [15]:
def count_occurrences(lst, elem):
    """
    Counts how many times a specific element appears in a nested list.

    Parameters:
    lst (list): A nested list containing numbers and/or other lists.
    elem: The element to count.

    Returns:
    int: The number of occurrences of elem in the nested list.
    """
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        else:
            if item == elem:
                count += 1
    return count

nested_list = [[1, 2], [2, 3], [2, 4]]
element = 2
result = count_occurrences(nested_list, element)

print("Nested list:", nested_list)
print(f"Occurrences of {element}:", result)

Nested list: [[1, 2], [2, 3], [2, 4]]
Occurrences of 2: 3


## 7. Flatten a List of Lists of Lists:

In [16]:
def deep_flatten(lst):
    """
    Flattens a deeply nested list into a single list, regardless of depth.

    Parameters:
    lst (list): A nested list (can contain lists within lists at any depth).

    Returns:
    list: A flattened list containing all elements.
    """
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(deep_flatten(item))
        else:
            flat_list.append(item)
    return flat_list

nested_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
result = deep_flatten(nested_list)

print("Original nested list:", nested_list)
print("Flattened list:", result)

Original nested list: [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
Flattened list: [1, 2, 3, 4, 5, 6, 7, 8]


## 8. Nested List Average:

In [17]:
def flatten_and_sum(lst):
    """Helper function: returns (total_sum, total_count) of elements in nested list"""
    total_sum = 0
    total_count = 0
    for item in lst:
        if isinstance(item, list):
            sub_sum, sub_count = flatten_and_sum(item)
            total_sum += sub_sum
            total_count += sub_count
        else:
            total_sum += item
            total_count += 1
    return total_sum, total_count

def average_nested(lst):
    """
    Calculates the average of all elements in a nested list, regardless of depth.

    Parameters:
    lst (list): A nested list containing numbers and/or other lists.

    Returns:
    float: The average of all numbers in the nested list.
    """

    total_sum, total_count = flatten_and_sum(lst)
    if total_count == 0:
        return 0
    return total_sum / total_count

nested_list = [[1, 2], [3, 4], [5, 6]]
result = average_nested(nested_list)

print("Nested list:", nested_list)
print("Average of all elements:", result)

Nested list: [[1, 2], [3, 4], [5, 6]]
Average of all elements: 3.5


## 10 To - Do - NumPy

In [18]:
import numpy as np

## 10.1 Basic Vector and Matrix Operation with Numpy.
## Problem - 1: Array Creation:

In [19]:
empty_array = np.empty((2, 2))
print("Empty 2x2 array:\n", empty_array)

Empty 2x2 array:
 [[ 5.32484190e-319  0.00000000e+000]
 [-1.09759049e-192 -4.47907930e-120]]


In [20]:
ones_array = np.ones((4, 2))
print("\nAll-one 4x2 array:\n", ones_array)


All-one 4x2 array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [21]:
fill_value = 7
filled_array = np.full((3, 3), fill_value, dtype=int)
print("\nFilled array with 7:\n", filled_array)


Filled array with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


In [22]:
given_array = np.array([[5, 6], [7, 8]])
zeros_like_array = np.zeros_like(given_array)
print("\nZeros like given array:\n", zeros_like_array)


Zeros like given array:
 [[0 0]
 [0 0]]


In [23]:
ones_like_array = np.ones_like(given_array)
print("\nOnes like given array:\n", ones_like_array)


Ones like given array:
 [[1 1]
 [1 1]]


In [24]:
new_list = [1, 2, 3, 4]
array_from_list = np.array(new_list)
print("\nNumPy array from list:", array_from_list)


NumPy array from list: [1 2 3 4]


## Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:


In [25]:
arr1 = np.arange(10, 50)
print("Array from 10 to 49:\n", arr1)

Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [26]:
arr2 = np.arange(9).reshape(3, 3)
print("\n3x3 matrix 0 to 8:\n", arr2)


3x3 matrix 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [27]:
identity_matrix = np.eye(3)
print("\n3x3 Identity matrix:\n", identity_matrix)


3x3 Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [28]:
random_array = np.random.random(30)
mean_value = random_array.mean()
print("\nRandom array (size 30):\n", random_array)
print("Mean of the array:", mean_value)


Random array (size 30):
 [0.11204845 0.72847493 0.15271642 0.00893229 0.51329545 0.59294161
 0.49562085 0.66863288 0.31506165 0.81939108 0.56966185 0.38641675
 0.43966508 0.66857499 0.78667518 0.45963626 0.57857885 0.82240876
 0.17305541 0.36574645 0.45276727 0.32927684 0.10458633 0.29829791
 0.01360485 0.68985424 0.5829396  0.93929169 0.12426604 0.27419799]
Mean of the array: 0.44888726425442127


In [29]:
rand_10x10 = np.random.random((10, 10))
min_val = rand_10x10.min()
max_val = rand_10x10.max()
print("\n10x10 Random array:\n", rand_10x10)
print("Min value:", min_val)
print("Max value:", max_val)


10x10 Random array:
 [[0.41893503 0.54145832 0.66590328 0.39665999 0.44533502 0.21333413
  0.68899592 0.20099129 0.88211377 0.54608431]
 [0.52589253 0.2434027  0.70522882 0.34476853 0.44646069 0.55361555
  0.20189537 0.5204287  0.13566579 0.56601471]
 [0.69122397 0.0206844  0.820668   0.63477543 0.2221568  0.51912208
  0.09173276 0.7777189  0.35375134 0.52414832]
 [0.51673277 0.24134298 0.76975456 0.85577139 0.20509034 0.04364487
  0.79169871 0.15488682 0.91351758 0.19846234]
 [0.44594129 0.89549789 0.66391187 0.46863587 0.71236549 0.30345654
  0.20840173 0.54342678 0.37518927 0.84815022]
 [0.23665619 0.65693581 0.52667061 0.02728843 0.20595891 0.43733575
  0.02105356 0.70452072 0.70613995 0.21676176]
 [0.30040094 0.51722593 0.13577838 0.47855618 0.68307078 0.49725262
  0.134283   0.21282232 0.39209856 0.12335004]
 [0.50663637 0.53331665 0.59843788 0.32453289 0.77778536 0.84347969
  0.87144895 0.85336515 0.77777582 0.86358427]
 [0.57212377 0.69227444 0.39041837 0.79785172 0.97335199 0

In [30]:
zero_array = np.zeros(10)
zero_array[4] = 1
print("\nZero array with 5th element as 1:\n", zero_array)


Zero array with 5th element as 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [31]:
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\nReversed array:\n", reversed_arr)


Reversed array:
 [0 4 0 0 2 1]


In [32]:
n = 5
border_array = np.ones((n, n))
border_array[1:-1, 1:-1] = 0
print("\n2D array with 1 on border, 0 inside:\n", border_array)


2D array with 1 on border, 0 inside:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [33]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n8x8 Checkerboard pattern:\n", checkerboard)


8x8 Checkerboard pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Problem - 3: Array Operations:

In [34]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

In [35]:
add_xy = x + y
print("x + y:\n", add_xy)
add_vw = v + w
print("v + w:\n", add_vw)

x + y:
 [[ 6  8]
 [10 13]]
v + w:
 [20 22]


In [36]:
sub_xy = x - y
print("x - y:\n", sub_xy)
sub_vw = v - w
print("v - w:\n", sub_vw)

x - y:
 [[-4 -4]
 [-4 -3]]
v - w:
 [-2 -2]


In [37]:
print("x * 3:\n", x*3)
print("y * 3:\n", y*3)
print("v * 3:\n", v*3)
print("w * 3:\n", w*3)

x * 3:
 [[ 3  6]
 [ 9 15]]
y * 3:
 [[15 18]
 [21 24]]
v * 3:
 [27 30]
w * 3:
 [33 36]


In [38]:
print("Square of x:\n", x ** 2)
print("Square of y:\n", y ** 2)
print("Square of v:\n", v ** 2)
print("Square of w:\n", w ** 2)

Square of x:
 [[ 1  4]
 [ 9 25]]
Square of y:
 [[25 36]
 [49 64]]
Square of v:
 [ 81 100]
Square of w:
 [121 144]


In [39]:
dot_vw = np.dot(v, w)
print("v · w:", dot_vw)
dot_xv = np.dot(x, v)
print("\nx · v:", dot_xv)
dot_xy = np.dot(x, y)
print("\nx · y:\n", dot_xy)

v · w: 219

x · v: [29 77]

x · y:
 [[19 22]
 [50 58]]


In [40]:
concat_xy_rows = np.concatenate((x, y), axis=0)
print("Concatenate x & y along rows:\n", concat_xy_rows)
concat_vw_cols = np.vstack((v, w)).T
print("\nConcatenate v & w as columns:\n", concat_vw_cols)

Concatenate x & y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate v & w as columns:
 [[ 9 11]
 [10 12]]


In [41]:
# There occurs an error because np.concatenate requires both array to be of same dimensions
try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("\Concatenate x & v:\n", concat_xv)
except ValueError as e:
    print("\nError when concatenating x & v:\n", e)


Error when concatenating x & v:
 all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


<>:4: SyntaxWarning: invalid escape sequence '\C'
<>:4: SyntaxWarning: invalid escape sequence '\C'
/tmp/ipykernel_215/3554039000.py:4: SyntaxWarning: invalid escape sequence '\C'
  print("\Concatenate x & v:\n", concat_xv)


## Problem - 4: Matrix Operations:


In [42]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

In [43]:
#A.A.inv = I
A_inv = np.linalg.inv(A)
result = np.dot(A, A_inv)
print(result)

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [44]:
#AB!=BA
AB = np.dot(A,B)
print(AB)
BA = np.dot(B,A)
print(BA)

[[23 13]
 [51 29]]
[[36 44]
 [13 16]]


In [45]:
# (AB)T=BTAT
left = (np.dot(A,B)).T
print(left)
right = np.dot(B.T, A.T)
print(right)

[[23 51]
 [13 29]]
[[23 51]
 [13 29]]


Solve the following system of Linear equation using Inverse Methods.<br>
2x − 3y + z = −1<br>
x − y + 2z = −3<br>
3x + y − z = 9

In [52]:
A = np.array([[2,-3,1],
              [1,-1,2],
              [3,1,-1]])
B = np.array([-1,-3,9])
A_inv = np.linalg.inv(A)
X = np.dot(A_inv,B)
print(X)

[ 2.  1. -2.]


## 10.2 Experiment: How Fast is Numpy?

In [53]:
import time

## Element-wise Addition

In [54]:
size = 1000000

list1 = list(range(size))
list2 = list(range(size))
start = time.time()
result = [list1[i] + list2[i] for i in range(size)]
end = time.time()
print("Python list addition time:", end - start)

Python list addition time: 0.12057018280029297


In [55]:
arr1 = np.arange(size)
arr2 = np.arange(size)
start = time.time()
result = arr1 + arr2
end = time.time()
print("NumPy addition time:", end - start)

NumPy addition time: 0.02788996696472168


## Element-wise Multiplication

In [56]:
start = time.time()
result = [list1[i] * list2[i] for i in range(size)]
end = time.time()
print("Python list multiplication time:", end - start)

Python list multiplication time: 0.24828171730041504


In [57]:
start = time.time()
result = arr1 * arr2
end = time.time()
print("NumPy multiplication time:", end - start)

NumPy multiplication time: 0.032155513763427734


## Dot Product

In [58]:
start = time.time()
dot = sum(list1[i] * list2[i] for i in range(size))
end = time.time()
print("Python list dot product time:", end - start)

Python list dot product time: 0.10838770866394043


In [59]:
start = time.time()
dot = np.dot(arr1, arr2)
end = time.time()
print("NumPy dot product time:", end - start)

NumPy dot product time: 0.0029926300048828125


## Matrix Multiplication

In [60]:
n = 1000

A = [[1]*n for _ in range(n)]
B = [[1]*n for _ in range(n)]
start = time.time()
result = [[0]*n for _ in range(n)]
for i in range(n):
    for j in range(n):
        for k in range(n):
            result[i][j] += A[i][k] * B[k][j]
end = time.time()
print("Python list matrix multiplication time:", end - start)

Python list matrix multiplication time: 347.40059185028076


In [62]:
A = np.ones((1000,1000))
B = np.ones((1000,1000))
start = time.time()
result = np.dot(A,B)
end = time.time()
print("NumPy matrix multiplication time:", end - start)

NumPy matrix multiplication time: 0.06203603744506836
